# Dependencies
markdown:         kramdown
highlighter:      rouge
theme:            jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink:        pretty

# Setup
title:            Javier M
tagline:          'Works on my machine.'
description:      'Site Reliability Engineer. I build resilient systems and write about cloud, Kubernetes, and automation. Fueled by coffee, fascinated by mathematics, and occasionally lost in poetry.'
url:              https://xavetcghost.github.io
baseurl:          ""

author:
  name:           'Javier M'
  url:            https://xavetcghost.github.io

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
