# Dependencies
markdown:         kramdown
highlighter:      rouge
theme:            minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink:        pretty

# Setup
title:            Javier M
tagline:          'Works on my machine.'
description:      'Engineering, mathematics, writing, and other questionable ideas.'
url:              https://xavetcghost.github.io
baseurl:          ""

author:
  name:           'Javier M'
  url:            https://xavetcghost.github.io

# Navigation and theme
header_pages:
  - index.html
  - about.md

show_excerpts:    false

minima:
  date_format: "%b %-d, %Y"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
